import { createSelector } from '@ngrx/store';
import { QuizView } from '../../../core/models/quiz.model';
import { quizFeature } from './quiz.reducer';

// Base state-slice selectors are generated by createFeature (see quiz.reducer.ts).
export const {
  selectUser,
  selectQuestions,
  selectAnswers,
  selectStep,
  selectLoading,
  selectError,
} = quizFeature;

// The persistable slice of progress (no questions/loading/error).
export const selectProgress = createSelector(
  selectUser,
  selectAnswers,
  selectStep,
  (user, answers, step) => ({ user, answers, step })
);

// `step` drives the view: 0 = intro, 1..N = the Nth question, > N = results.
// Questions are therefore indexed with `step - 1` (see selectCurrentQuestion).
export const selectView = createSelector(
  selectStep,
  selectQuestions,
  (step, questions): QuizView => {
    if (step === 0) return 'INTRO';
    if (step > questions.length) return 'RESULTS';
    return 'QUESTION';
  }
);

export const selectCurrentQuestion = createSelector(
  selectQuestions,
  selectStep,
  (q, step) => q[step - 1] ?? null
);

export const selectCurrentAnswer = createSelector(selectAnswers, selectCurrentQuestion, (a, q) =>
  q ? a[q.id] ?? null : null
);

export const selectProgressPercent = createSelector(
  selectStep,
  selectQuestions,
  (step, q) => (step / Math.max(1, q.length + 1)) * 100
);

export const selectTotalScore = createSelector(
  selectQuestions,
  selectAnswers,
  (questions, answers) =>
    questions.reduce((sum, q) => {
      const a = answers[q.id];
      if (!a) return sum;

      if (q.type === 'single') {
        const picked = typeof a === 'string' ? a : null;
        return sum + (q.choices.find((c) => c.id === picked)?.isCorrect ? q.points : 0);
      }

      // Multiple choice: award points only when the selected set matches the
      // correct set exactly — no missing and no extra (wrong) selections.
      const selected = Array.isArray(a) ? a : [];
      const correct = q.choices.filter((c) => c.isCorrect).map((c) => c.id);
      const correctSet = new Set(correct);
      const isExact =
        selected.length === correct.length && selected.every((id) => correctSet.has(id));
      return isExact ? sum + q.points : sum;
    }, 0)
);

// Single view-model for the shell, so the template subscribes once with one
// `| async` and renders from an atomic snapshot.
export const selectQuizViewModel = createSelector(
  selectView,
  selectLoading,
  selectError,
  selectUser,
  selectCurrentQuestion,
  selectCurrentAnswer,
  selectProgressPercent,
  selectTotalScore,
  (view, loading, error, user, question, answer, progress, score) => ({
    view,
    loading,
    error,
    user,
    question,
    answer,
    progress,
    score,
  })
);
